//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoConvert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterLoopingPlaylists {
            get {
                return ((bool)(this["FilterLoopingPlaylists"]));
            }
            set {
                this["FilterLoopingPlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepStreamOrder {
            get {
                return ((bool)(this["KeepStreamOrder"]));
            }
            set {
                this["KeepStreamOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterShortPlaylists {
            get {
                return ((bool)(this["FilterShortPlaylists"]));
            }
            set {
                this["FilterShortPlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int FilterShortPlaylistsValue {
            get {
                return ((int)(this["FilterShortPlaylistsValue"]));
            }
            set {
                this["FilterShortPlaylistsValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSSIF {
            get {
                return ((bool)(this["EnableSSIF"]));
            }
            set {
                this["EnableSSIF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ToolsPath {
            get {
                return ((string)(this["ToolsPath"]));
            }
            set {
                this["ToolsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DemuxLocation {
            get {
                return ((string)(this["DemuxLocation"]));
            }
            set {
                this["DemuxLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputLocation {
            get {
                return ((string)(this["OutputLocation"]));
            }
            set {
                this["OutputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Lastx264Ver {
            get {
                return ((string)(this["Lastx264Ver"]));
            }
            set {
                this["Lastx264Ver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastffmpegVer {
            get {
                return ((string)(this["LastffmpegVer"]));
            }
            set {
                this["LastffmpegVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Lasteac3toVer {
            get {
                return ((string)(this["Lasteac3toVer"]));
            }
            set {
                this["Lasteac3toVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastlsdvdVer {
            get {
                return ((string)(this["LastlsdvdVer"]));
            }
            set {
                this["LastlsdvdVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool x264WithLavf {
            get {
                return ((bool)(this["x264WithLavf"]));
            }
            set {
                this["x264WithLavf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool x264WithGpac {
            get {
                return ((bool)(this["x264WithGpac"]));
            }
            set {
                this["x264WithGpac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool x264WithAVS {
            get {
                return ((bool)(this["x264WithAVS"]));
            }
            set {
                this["x264WithAVS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMKVMergeVer {
            get {
                return ((string)(this["LastMKVMergeVer"]));
            }
            set {
                this["LastMKVMergeVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMplayerVer {
            get {
                return ((string)(this["LastMplayerVer"]));
            }
            set {
                this["LastMplayerVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTSMuxerVer {
            get {
                return ((string)(this["LastTSMuxerVer"]));
            }
            set {
                this["LastTSMuxerVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tsMuxeRUseAsyncIO {
            get {
                return ((bool)(this["tsMuxeRUseAsyncIO"]));
            }
            set {
                this["tsMuxeRUseAsyncIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tsMuxeRBlurayAudioPES {
            get {
                return ((bool)(this["tsMuxeRBlurayAudioPES"]));
            }
            set {
                this["tsMuxeRBlurayAudioPES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int tsMuxerSubtitleAdditionalBorder {
            get {
                return ((int)(this["tsMuxerSubtitleAdditionalBorder"]));
            }
            set {
                this["tsMuxerSubtitleAdditionalBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int tsMuxeRBottomOffset {
            get {
                return ((int)(this["tsMuxeRBottomOffset"]));
            }
            set {
                this["tsMuxeRBottomOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tsMuxeRVideoTimingInfo {
            get {
                return ((bool)(this["tsMuxeRVideoTimingInfo"]));
            }
            set {
                this["tsMuxeRVideoTimingInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tsMuxeRAddVideoPPS {
            get {
                return ((bool)(this["tsMuxeRAddVideoPPS"]));
            }
            set {
                this["tsMuxeRAddVideoPPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteCompletedJobs {
            get {
                return ((bool)(this["DeleteCompletedJobs"]));
            }
            set {
                this["DeleteCompletedJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ProcessPriority {
            get {
                return ((int)(this["ProcessPriority"]));
            }
            set {
                this["ProcessPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMJPEGtoolsVer {
            get {
                return ((string)(this["LastMJPEGtoolsVer"]));
            }
            set {
                this["LastMJPEGtoolsVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDVDAuthorVer {
            get {
                return ((string)(this["LastDVDAuthorVer"]));
            }
            set {
                this["LastDVDAuthorVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteTemporaryFiles {
            get {
                return ((bool)(this["DeleteTemporaryFiles"]));
            }
            set {
                this["DeleteTemporaryFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDebug {
            get {
                return ((bool)(this["UseDebug"]));
            }
            set {
                this["UseDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAviSynthVer {
            get {
                return ((string)(this["LastAviSynthVer"]));
            }
            set {
                this["LastAviSynthVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system")]
        public string UseLanguage {
            get {
                return ((string)(this["UseLanguage"]));
            }
            set {
                this["UseLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMp4BoxVer {
            get {
                return ((string)(this["LastMp4BoxVer"]));
            }
            set {
                this["LastMp4BoxVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastHcEncVer {
            get {
                return ((string)(this["LastHcEncVer"]));
            }
            set {
                this["LastHcEncVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int tsMuxeRSubtitleFontSize {
            get {
                return ((int)(this["tsMuxeRSubtitleFontSize"]));
            }
            set {
                this["tsMuxeRSubtitleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public global::System.Windows.Media.FontFamily tsMuxeRSubtitleFont {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["tsMuxeRSubtitleFont"]));
            }
            set {
                this["tsMuxeRSubtitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color tsMuxeRSubtitleColor {
            get {
                return ((global::System.Windows.Media.Color)(this["tsMuxeRSubtitleColor"]));
            }
            set {
                this["tsMuxeRSubtitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JavaInstallPath {
            get {
                return ((string)(this["JavaInstallPath"]));
            }
            set {
                this["JavaInstallPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBDSup2SubVer {
            get {
                return ((string)(this["LastBDSup2SubVer"]));
            }
            set {
                this["LastBDSup2SubVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseHardwareRendering {
            get {
                return ((bool)(this["UseHardwareRendering"]));
            }
            set {
                this["UseHardwareRendering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0.0")]
        public string UpdaterVersion {
            get {
                return ((string)(this["UpdaterVersion"]));
            }
            set {
                this["UpdaterVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedProfile {
            get {
                return ((string)(this["LastSelectedProfile"]));
            }
            set {
                this["LastSelectedProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAviSynthMT {
            get {
                return ((bool)(this["UseAviSynthMT"]));
            }
            set {
                this["UseAviSynthMT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAviSynthPluginsVer {
            get {
                return ((string)(this["LastAviSynthPluginsVer"]));
            }
            set {
                this["LastAviSynthPluginsVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseHQDeinterlace {
            get {
                return ((bool)(this["UseHQDeinterlace"]));
            }
            set {
                this["UseHQDeinterlace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastOggEncVer {
            get {
                return ((string)(this["LastOggEncVer"]));
            }
            set {
                this["LastOggEncVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLameVer {
            get {
                return ((string)(this["LastLameVer"]));
            }
            set {
                this["LastLameVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNeroAacEncVer {
            get {
                return ((string)(this["LastNeroAacEncVer"]));
            }
            set {
                this["LastNeroAacEncVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateVersions {
            get {
                return ((bool)(this["UpdateVersions"]));
            }
            set {
                this["UpdateVersions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVpxEncVer {
            get {
                return ((string)(this["LastVpxEncVer"]));
            }
            set {
                this["LastVpxEncVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProfilesVer {
            get {
                return ((string)(this["LastProfilesVer"]));
            }
            set {
                this["LastProfilesVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Lastx264_64Ver {
            get {
                return ((string)(this["Lastx264_64Ver"]));
            }
            set {
                this["Lastx264_64Ver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Use64bitEncoders {
            get {
                return ((bool)(this["Use64bitEncoders"]));
            }
            set {
                this["Use64bitEncoders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpdateFrequency {
            get {
                return ((int)(this["UpdateFrequency"]));
            }
            set {
                this["UpdateFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2012-12-25")]
        public global::System.DateTime LastUpdateRun {
            get {
                return ((global::System.DateTime)(this["LastUpdateRun"]));
            }
            set {
                this["LastUpdateRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowChangeLog {
            get {
                return ((bool)(this["ShowChangeLog"]));
            }
            set {
                this["ShowChangeLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Lastffmpeg_64Ver {
            get {
                return ((string)(this["Lastffmpeg_64Ver"]));
            }
            set {
                this["Lastffmpeg_64Ver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateXbmcInfoFile {
            get {
                return ((bool)(this["CreateXbmcInfoFile"]));
            }
            set {
                this["CreateXbmcInfoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string MovieDBLastLanguage {
            get {
                return ((string)(this["MovieDBLastLanguage"]));
            }
            set {
                this["MovieDBLastLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("us")]
        public string MovieDBLastRatingCountry {
            get {
                return ((string)(this["MovieDBLastRatingCountry"]));
            }
            set {
                this["MovieDBLastRatingCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string MovieDBLastFallbackLanguage {
            get {
                return ((string)(this["MovieDBLastFallbackLanguage"]));
            }
            set {
                this["MovieDBLastFallbackLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("us")]
        public string MovieDBLastFallbackRatingCountry {
            get {
                return ((string)(this["MovieDBLastFallbackRatingCountry"]));
            }
            set {
                this["MovieDBLastFallbackRatingCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rated ")]
        public string MovieDBPreferredCertPrefix {
            get {
                return ((string)(this["MovieDBPreferredCertPrefix"]));
            }
            set {
                this["MovieDBPreferredCertPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rated ")]
        public string MovieDBFallbackCertPrefix {
            get {
                return ((string)(this["MovieDBFallbackCertPrefix"]));
            }
            set {
                this["MovieDBFallbackCertPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MovieDBRatingSource {
            get {
                return ((int)(this["MovieDBRatingSource"]));
            }
            set {
                this["MovieDBRatingSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TvDBCachePath {
            get {
                return ((string)(this["TvDBCachePath"]));
            }
            set {
                this["TvDBCachePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TvDBParseString {
            get {
                return ((string)(this["TvDBParseString"]));
            }
            set {
                this["TvDBParseString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string TvDBPreferredLanguage {
            get {
                return ((string)(this["TvDBPreferredLanguage"]));
            }
            set {
                this["TvDBPreferredLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string TvDBFallbackLanguage {
            get {
                return ((string)(this["TvDBFallbackLanguage"]));
            }
            set {
                this["TvDBFallbackLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSelectedSource {
            get {
                return ((int)(this["LastSelectedSource"]));
            }
            set {
                this["LastSelectedSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFfmpegScaling {
            get {
                return ((bool)(this["UseFfmpegScaling"]));
            }
            set {
                this["UseFfmpegScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LimitDecoderThreads {
            get {
                return ((bool)(this["LimitDecoderThreads"]));
            }
            set {
                this["LimitDecoderThreads"] = value;
            }
        }
    }
}
