using System.Collections.Generic;

namespace VideoConvert.Core.Helpers.TheMovieDB
{
    public static class MovieDBLanguages
    {
        public static List<MovieDBLanguage> LangList { get { return GenerateLangList(); } }

        private static List<MovieDBLanguage> GenerateLangList()
        {
            List<MovieDBLanguage> result = new List<MovieDBLanguage>
                {
                    new MovieDBLanguage {Code = "aa", Name = "Afar"},
                    new MovieDBLanguage {Code = "ab", Name = "Аҧсуа"},
                    new MovieDBLanguage {Code = "af", Name = "Afrikaans"},
                    new MovieDBLanguage {Code = "ak", Name = "Akana"},
                    new MovieDBLanguage {Code = "als", Name = "Alemannisch"},
                    new MovieDBLanguage {Code = "am", Name = "አማርኛ"},
                    new MovieDBLanguage {Code = "an", Name = "Aragonés"},
                    new MovieDBLanguage {Code = "ang", Name = "Englisc"},
                    new MovieDBLanguage {Code = "ar", Name = "العربية"},
                    new MovieDBLanguage {Code = "arc", Name = "Aramaic"},
                    new MovieDBLanguage {Code = "as", Name = "Assamese"},
                    new MovieDBLanguage {Code = "ast", Name = "Asturianu"},
                    new MovieDBLanguage {Code = "av", Name = "Авар"},
                    new MovieDBLanguage {Code = "ay", Name = "Aymar"},
                    new MovieDBLanguage {Code = "az", Name = "Azərbaycanca / آذربايجان"},
                    new MovieDBLanguage {Code = "ba", Name = "Башҡорт"},
                    new MovieDBLanguage {Code = "bar", Name = "Boarisch"},
                    new MovieDBLanguage {Code = "bat-smg", Name = "Žemaitėška"},
                    new MovieDBLanguage {Code = "bcl", Name = "Bikol Central"},
                    new MovieDBLanguage {Code = "be", Name = "Беларуская"},
                    new MovieDBLanguage {Code = "be-x-old", Name = "Беларуская (тарашкевіца)"},
                    new MovieDBLanguage {Code = "bg", Name = "Български"},
                    new MovieDBLanguage {Code = "bh", Name = "Bihari"},
                    new MovieDBLanguage {Code = "bi", Name = "Bislama"},
                    new MovieDBLanguage {Code = "bm", Name = "Bamanankan"},
                    new MovieDBLanguage {Code = "bn", Name = "Bengali"},
                    new MovieDBLanguage {Code = "bo", Name = "Tibetan"},
                    new MovieDBLanguage {Code = "bpy", Name = "Bishnupriya Manipuri"},
                    new MovieDBLanguage {Code = "br", Name = "Brezhoneg"},
                    new MovieDBLanguage {Code = "bs", Name = "Bosanski"},
                    new MovieDBLanguage {Code = "bug", Name = "Buginese"},
                    new MovieDBLanguage {Code = "bxr", Name = "Буряад хэлэн"},
                    new MovieDBLanguage {Code = "ca", Name = "Català"},
                    new MovieDBLanguage {Code = "ce", Name = "Нохчийн"},
                    new MovieDBLanguage {Code = "ceb", Name = "Sinugboanong Binisaya"},
                    new MovieDBLanguage {Code = "ch", Name = "Chamoru"},
                    new MovieDBLanguage {Code = "cho", Name = "Choctaw"},
                    new MovieDBLanguage {Code = "chr", Name = "ᏣᎳᎩ"},
                    new MovieDBLanguage {Code = "chy", Name = "Tsetsêhestâhese"},
                    new MovieDBLanguage {Code = "co", Name = "Corsu"},
                    new MovieDBLanguage {Code = "cr", Name = "Nehiyaw"},
                    new MovieDBLanguage {Code = "cs", Name = "Česky"},
                    new MovieDBLanguage {Code = "csb", Name = "Kaszëbsczi"},
                    new MovieDBLanguage {Code = "cu", Name = "словѣньскъ / slověnĭskŭ"},
                    new MovieDBLanguage {Code = "cv", Name = "Чăваш"},
                    new MovieDBLanguage {Code = "cy", Name = "Cymraeg"},
                    new MovieDBLanguage {Code = "da", Name = "Dansk"},
                    new MovieDBLanguage {Code = "de", Name = "Deutsch"},
                    new MovieDBLanguage {Code = "diq", Name = "Zazaki"},
                    new MovieDBLanguage {Code = "dsb", Name = "Dolnoserbski"},
                    new MovieDBLanguage {Code = "dv", Name = "Divehi"},
                    new MovieDBLanguage {Code = "dz", Name = "Dzongkha"},
                    new MovieDBLanguage {Code = "ee", Name = "Ɛʋɛ"},
                    new MovieDBLanguage {Code = "el", Name = "Ελληνικά"},
                    new MovieDBLanguage {Code = "en", Name = "English"},
                    new MovieDBLanguage {Code = "eo", Name = "Esperanto"},
                    new MovieDBLanguage {Code = "es", Name = "Español"},
                    new MovieDBLanguage {Code = "et", Name = "Eesti"},
                    new MovieDBLanguage {Code = "eu", Name = "Euskara"},
                    new MovieDBLanguage {Code = "ext", Name = "Estremeñu"},
                    new MovieDBLanguage {Code = "fa", Name = "فارسی"},
                    new MovieDBLanguage {Code = "ff", Name = "Fulfulde"},
                    new MovieDBLanguage {Code = "fi", Name = "Suomi"},
                    new MovieDBLanguage {Code = "fiu-vro", Name = "Võro"},
                    new MovieDBLanguage {Code = "fj", Name = "Na Vosa Vakaviti"},
                    new MovieDBLanguage {Code = "fo", Name = "Føroyskt"},
                    new MovieDBLanguage {Code = "fr", Name = "Français"},
                    new MovieDBLanguage {Code = "frp", Name = "Arpitan / francoprovençal"},
                    new MovieDBLanguage {Code = "fur", Name = "Furlan"},
                    new MovieDBLanguage {Code = "fy", Name = "Frysk"},
                    new MovieDBLanguage {Code = "ga", Name = "Gaeilge"},
                    new MovieDBLanguage {Code = "gd", Name = "Gàidhlig"},
                    new MovieDBLanguage {Code = "gil", Name = "Taetae ni kiribati"},
                    new MovieDBLanguage {Code = "gl", Name = "Galego"},
                    new MovieDBLanguage {Code = "gn", Name = "Avañe'ẽ"},
                    new MovieDBLanguage {Code = "got", Name = "gutisk"},
                    new MovieDBLanguage {Code = "gu", Name = "Gujarati"},
                    new MovieDBLanguage {Code = "gv", Name = "Gaelg"},
                    new MovieDBLanguage {Code = "ha", Name = "Hausa"},
                    new MovieDBLanguage {Code = "haw", Name = "Hawai`i"},
                    new MovieDBLanguage {Code = "he", Name = "עברית"},
                    new MovieDBLanguage {Code = "hi", Name = "हिन्दी"},
                    new MovieDBLanguage {Code = "ho", Name = "Hiri Motu"},
                    new MovieDBLanguage {Code = "hr", Name = "Hrvatski"},
                    new MovieDBLanguage {Code = "ht", Name = "Krèyol ayisyen"},
                    new MovieDBLanguage {Code = "hu", Name = "Magyar"},
                    new MovieDBLanguage {Code = "hy", Name = "Հայերեն"},
                    new MovieDBLanguage {Code = "hz", Name = "Otsiherero"},
                    new MovieDBLanguage {Code = "ia", Name = "Interlingua"},
                    new MovieDBLanguage {Code = "id", Name = "Bahasa Indonesia"},
                    new MovieDBLanguage {Code = "ie", Name = "Interlingue"},
                    new MovieDBLanguage {Code = "ig", Name = "Igbo"},
                    new MovieDBLanguage {Code = "ii", Name = "ꆇꉙ / 四川彝语"},
                    new MovieDBLanguage {Code = "ik", Name = "Iñupiak"},
                    new MovieDBLanguage {Code = "ilo", Name = "Ilokano"},
                    new MovieDBLanguage {Code = "io", Name = "Ido"},
                    new MovieDBLanguage {Code = "is", Name = "Íslenska"},
                    new MovieDBLanguage {Code = "it", Name = "Italiano"},
                    new MovieDBLanguage {Code = "iu", Name = "ᐃᓄᒃᑎᑐᑦ"},
                    new MovieDBLanguage {Code = "ja", Name = "日本語"},
                    new MovieDBLanguage {Code = "jbo", Name = "Lojban"},
                    new MovieDBLanguage {Code = "jv", Name = "Basa Jawa"},
                    new MovieDBLanguage {Code = "ka", Name = "ქართული"},
                    new MovieDBLanguage {Code = "kg", Name = "KiKongo"},
                    new MovieDBLanguage {Code = "ki", Name = "Gĩkũyũ"},
                    new MovieDBLanguage {Code = "kj", Name = "Kuanyama"},
                    new MovieDBLanguage {Code = "kk", Name = "Қазақша"},
                    new MovieDBLanguage {Code = "kl", Name = "Kalaallisut"},
                    new MovieDBLanguage {Code = "km", Name = "Cambodian"},
                    new MovieDBLanguage {Code = "kn", Name = "ಕನ್ನಡ"},
                    new MovieDBLanguage {Code = "khw", Name = "کھوار"},
                    new MovieDBLanguage {Code = "ko", Name = "한국어"},
                    new MovieDBLanguage {Code = "kr", Name = "Kanuri"},
                    new MovieDBLanguage {Code = "ks", Name = "कश्मीरी / كشميري"},
                    new MovieDBLanguage {Code = "ksh", Name = "Ripoarisch"},
                    new MovieDBLanguage {Code = "ku", Name = "Kurdî / كوردی"},
                    new MovieDBLanguage {Code = "kv", Name = "Коми"},
                    new MovieDBLanguage {Code = "kw", Name = "Kernewek"},
                    new MovieDBLanguage {Code = "ky", Name = "Kırgızca / Кыргызча"},
                    new MovieDBLanguage {Code = "la", Name = "Latina"},
                    new MovieDBLanguage {Code = "lad", Name = "Dzhudezmo / Djudeo-Espanyol"},
                    new MovieDBLanguage {Code = "lan", Name = "Leb Lango / Luo"},
                    new MovieDBLanguage {Code = "lb", Name = "Lëtzebuergesch"},
                    new MovieDBLanguage {Code = "lg", Name = "Luganda"},
                    new MovieDBLanguage {Code = "li", Name = "Limburgs"},
                    new MovieDBLanguage {Code = "lij", Name = "Líguru"},
                    new MovieDBLanguage {Code = "lmo", Name = "Lumbaart"},
                    new MovieDBLanguage {Code = "ln", Name = "Lingála"},
                    new MovieDBLanguage {Code = "lo", Name = "ລາວ / Pha xa lao"},
                    new MovieDBLanguage {Code = "lt", Name = "Lietuvių"},
                    new MovieDBLanguage {Code = "lv", Name = "Latviešu"},
                    new MovieDBLanguage {Code = "map-bms", Name = "Basa Banyumasan"},
                    new MovieDBLanguage {Code = "mg", Name = "Malagasy"},
                    new MovieDBLanguage {Code = "mh", Name = "Kajin Majel / Ebon"},
                    new MovieDBLanguage {Code = "mi", Name = "Māori"},
                    new MovieDBLanguage {Code = "min", Name = "Minangkabau"},
                    new MovieDBLanguage {Code = "mk", Name = "Македонски"},
                    new MovieDBLanguage {Code = "ml", Name = "Malayalam"},
                    new MovieDBLanguage {Code = "mn", Name = "Монгол"},
                    new MovieDBLanguage {Code = "mo", Name = "Moldovenească"},
                    new MovieDBLanguage {Code = "mr", Name = "मराठी"},
                    new MovieDBLanguage {Code = "ms", Name = "Bahasa Melayu"},
                    new MovieDBLanguage {Code = "mt", Name = "bil-Malti"},
                    new MovieDBLanguage {Code = "mus", Name = "Mvskoke"},
                    new MovieDBLanguage {Code = "my", Name = "Myanmasa"},
                    new MovieDBLanguage {Code = "na", Name = "Dorerin Naoero"},
                    new MovieDBLanguage {Code = "nah", Name = "Nahuatl"},
                    new MovieDBLanguage {Code = "nap", Name = "Nnapulitano"},
                    new MovieDBLanguage {Code = "nd", Name = "Sindebele"},
                    new MovieDBLanguage {Code = "nds", Name = "Plattdüütsch"},
                    new MovieDBLanguage {Code = "nds-nl", Name = "Nedersaksisch"},
                    new MovieDBLanguage {Code = "ne", Name = "नेपाली"},
                    new MovieDBLanguage {Code = "new", Name = "नेपालभाषा / Newah Bhaye"},
                    new MovieDBLanguage {Code = "ng", Name = "Oshiwambo"},
                    new MovieDBLanguage {Code = "nl", Name = "Nederlands"},
                    new MovieDBLanguage {Code = "nn", Name = "Norsk (nynorsk)"},
                    new MovieDBLanguage {Code = "no", Name = "Norsk (bokmål / riksmål)"},
                    new MovieDBLanguage {Code = "nr", Name = "isiNdebele"},
                    new MovieDBLanguage {Code = "nso", Name = "Sesotho sa Leboa / Sepedi"},
                    new MovieDBLanguage {Code = "nrm", Name = "Nouormand / Normaund"},
                    new MovieDBLanguage {Code = "nv", Name = "Diné bizaad"},
                    new MovieDBLanguage {Code = "ny", Name = "Chi-Chewa"},
                    new MovieDBLanguage {Code = "oc", Name = "Occitan"},
                    new MovieDBLanguage {Code = "oj", Name = "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin"},
                    new MovieDBLanguage {Code = "om", Name = "Oromoo"},
                    new MovieDBLanguage {Code = "or", Name = "Oriya"},
                    new MovieDBLanguage {Code = "os", Name = "Иронау"},
                    new MovieDBLanguage {Code = "pa", Name = "Panjabi / Punjabi"},
                    new MovieDBLanguage {Code = "pag", Name = "Pangasinan"},
                    new MovieDBLanguage {Code = "pam", Name = "Kapampangan"},
                    new MovieDBLanguage {Code = "pap", Name = "Papiamentu"},
                    new MovieDBLanguage {Code = "pdc", Name = "Deitsch"},
                    new MovieDBLanguage {Code = "pi", Name = "Pāli / पाऴि"},
                    new MovieDBLanguage {Code = "pih", Name = "Norfuk"},
                    new MovieDBLanguage {Code = "pl", Name = "Polski"},
                    new MovieDBLanguage {Code = "pms", Name = "Piemontèis"},
                    new MovieDBLanguage {Code = "ps", Name = "پښتو"},
                    new MovieDBLanguage {Code = "pt", Name = "Português"},
                    new MovieDBLanguage {Code = "qu", Name = "Runa Simi"},
                    new MovieDBLanguage {Code = "rm", Name = "Rumantsch"},
                    new MovieDBLanguage {Code = "rmy", Name = "Romani / रोमानी"},
                    new MovieDBLanguage {Code = "rn", Name = "Kirundi"},
                    new MovieDBLanguage {Code = "ro", Name = "Română"},
                    new MovieDBLanguage {Code = "roa-rup", Name = "Armâneashti"},
                    new MovieDBLanguage {Code = "ru", Name = "Русский"},
                    new MovieDBLanguage {Code = "rw", Name = "Kinyarwandi"},
                    new MovieDBLanguage {Code = "sa", Name = "संस्कृतम्"},
                    new MovieDBLanguage {Code = "sc", Name = "Sardu"},
                    new MovieDBLanguage {Code = "scn", Name = "Sicilianu"},
                    new MovieDBLanguage {Code = "sco", Name = "Scots"},
                    new MovieDBLanguage {Code = "sd", Name = "सिनधि"},
                    new MovieDBLanguage {Code = "se", Name = "Sámegiella"},
                    new MovieDBLanguage {Code = "sg", Name = "Sängö"},
                    new MovieDBLanguage {Code = "sh", Name = "Srpskohrvatski / Српскохрватски"},
                    new MovieDBLanguage {Code = "si", Name = "Sinhalese"},
                    new MovieDBLanguage {Code = "simple", Name = "Simple English"},
                    new MovieDBLanguage {Code = "sk", Name = "Slovenčina"},
                    new MovieDBLanguage {Code = "sl", Name = "Slovenščina"},
                    new MovieDBLanguage {Code = "sm", Name = "Gagana Samoa"},
                    new MovieDBLanguage {Code = "sn", Name = "chiShona"},
                    new MovieDBLanguage {Code = "so", Name = "Soomaaliga"},
                    new MovieDBLanguage {Code = "sq", Name = "Shqip"},
                    new MovieDBLanguage {Code = "sr", Name = "Српски"},
                    new MovieDBLanguage {Code = "ss", Name = "SiSwati"},
                    new MovieDBLanguage {Code = "st", Name = "Sesotho"},
                    new MovieDBLanguage {Code = "su", Name = "Basa Sunda"},
                    new MovieDBLanguage {Code = "sv", Name = "Svenska"},
                    new MovieDBLanguage {Code = "sw", Name = "Kiswahili"},
                    new MovieDBLanguage {Code = "ta", Name = "Tamil"},
                    new MovieDBLanguage {Code = "te", Name = "Telugu"},
                    new MovieDBLanguage {Code = "tet", Name = "Tetun"},
                    new MovieDBLanguage {Code = "tg", Name = "Тоҷикӣ"},
                    new MovieDBLanguage {Code = "th", Name = "ไทย / Phasa Thai"},
                    new MovieDBLanguage {Code = "ti", Name = "ትግርኛ"},
                    new MovieDBLanguage {Code = "tk", Name = "Туркмен / تركمن"},
                    new MovieDBLanguage {Code = "tl", Name = "Tagalog"},
                    new MovieDBLanguage {Code = "tlh", Name = "tlhIngan-Hol"},
                    new MovieDBLanguage {Code = "tn", Name = "Setswana"},
                    new MovieDBLanguage {Code = "to", Name = "Lea Faka-Tonga"},
                    new MovieDBLanguage {Code = "tpi", Name = "Tok Pisin"},
                    new MovieDBLanguage {Code = "tr", Name = "Türkçe"},
                    new MovieDBLanguage {Code = "ts", Name = "Xitsonga"},
                    new MovieDBLanguage {Code = "tt", Name = "Tatarça"},
                    new MovieDBLanguage {Code = "tum", Name = "chiTumbuka"},
                    new MovieDBLanguage {Code = "tw", Name = "Twi"},
                    new MovieDBLanguage {Code = "ty", Name = "Reo Mā`ohi"},
                    new MovieDBLanguage {Code = "udm", Name = "Удмурт кыл"},
                    new MovieDBLanguage {Code = "ug", Name = "Uyƣurqə / ئۇيغۇرچە"},
                    new MovieDBLanguage {Code = "uk", Name = "Українська"},
                    new MovieDBLanguage {Code = "ur", Name = "اردو"},
                    new MovieDBLanguage {Code = "uz", Name = "Ўзбек"},
                    new MovieDBLanguage {Code = "ve", Name = "Tshivenḓa"},
                    new MovieDBLanguage {Code = "vi", Name = "Tiếng Việt"},
                    new MovieDBLanguage {Code = "vec", Name = "Vèneto"},
                    new MovieDBLanguage {Code = "vls", Name = "West-Vlaoms"},
                    new MovieDBLanguage {Code = "vo", Name = "Volapük"},
                    new MovieDBLanguage {Code = "wa", Name = "Walon"},
                    new MovieDBLanguage {Code = "war", Name = "Winaray / Binisaya Lineyte-Samarnon"},
                    new MovieDBLanguage {Code = "wo", Name = "Wollof"},
                    new MovieDBLanguage {Code = "xal", Name = "Хальмг"},
                    new MovieDBLanguage {Code = "xh", Name = "isiXhosa"},
                    new MovieDBLanguage {Code = "yi", Name = "ייִדיש"},
                    new MovieDBLanguage {Code = "yo", Name = "Yorùbá"},
                    new MovieDBLanguage {Code = "za", Name = "Cuengh / Tôô / 壮语"},
                    new MovieDBLanguage {Code = "zh", Name = "中文"},
                    new MovieDBLanguage {Code = "zh-min-nan", Name = "Bân-lâm-gú"},
                    new MovieDBLanguage {Code = "zh-yue", Name = "粵語 / 粤语"},
                    new MovieDBLanguage {Code = "zu", Name = "isiZulu"}
                };

            return result;
        }
    }
}
