// --------------------------------------------------------------------------------------------------------------------
// <copyright file="LanguageHelper.cs" company="JT-Soft (https://github.com/UniqProject/VideoConvert)">
//   This file is part of the VideoConvert.Interop source code - It may be used under the terms of the GNU General Public License.
// </copyright>
// <summary>
//   Helper class for ISO639 codes
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace VideoConvert.Interop.Utilities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Helper class for ISO639 codes
    /// </summary>
    public class LanguageHelper
    {
        private readonly string _iso1Lang;
        private readonly string _iso2Lang;
        private readonly string _fullLang;

        /// <summary>
        /// ISO639-1 language code
        /// </summary>
        public string Iso1Lang { get { return _iso1Lang; } }

        /// <summary>
        /// ISO639-2 language code
        /// </summary>
        public string Iso2Lang { get { return _iso2Lang; } }

        /// <summary>
        /// Full language name
        /// </summary>
        public string FullLang { get { return _fullLang; } }

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="iso1">ISO639-1 language code</param>
        /// <param name="iso2">ISO639-2 language code</param>
        /// <param name="full">Full language name</param>
        public LanguageHelper(string iso1, string iso2, string full)
        {
            _iso1Lang = iso1;
            _iso2Lang = iso2;
            _fullLang = full;
        }

        /// <summary>
        /// Search for language
        /// </summary>
        /// <param name="lang">search language</param>
        /// <returns></returns>
        public static LanguageHelper GetLanguage(string lang)
        {
            var langList = GenerateList();
            LanguageHelper ret;

            try
            {
                switch (lang.Length)
                {
                    case 2:
                        ret = (langList.Where(c => c._iso1Lang == lang)).First();
                        break;
                    case 3:
                        ret = (langList.Where(c => c._iso2Lang == lang)).First();
                        break;
                    default:
                        ret = (langList.Where(c => c._fullLang == lang)).First();
                        break;
                }
            }
            catch (Exception)
            {
                ret = (langList.Where(c => c._iso1Lang == "xx")).First();
            }
            return ret;
        }

        private static List<LanguageHelper> GenerateList()
        {
            var langList = new List<LanguageHelper>
            {
                new LanguageHelper("ab", "abk", "Abkhazian"),
                new LanguageHelper(string.Empty, "ace", "Achinese"),
                new LanguageHelper(string.Empty, "ach", "Acoli"),
                new LanguageHelper(string.Empty, "ada", "Adangme"),
                new LanguageHelper(string.Empty, "ady", "Adyghe / Adygei"),
                new LanguageHelper("aa", "aar", "Afar"),
                new LanguageHelper(string.Empty, "afh", "Afrihili"),
                new LanguageHelper("af", "afr", "Afrikaans"),
                new LanguageHelper(string.Empty, "afa", "Afro-Asiatic languages"),
                new LanguageHelper(string.Empty, "ain", "Ainu"),
                new LanguageHelper("ak", "aka", "Akan"),
                new LanguageHelper(string.Empty, "akk", "Akkadian"),
                new LanguageHelper("sq", "alb", "Albanian"),
                new LanguageHelper(string.Empty, "ale", "Aleut"),
                new LanguageHelper(string.Empty, "alg", "Algonquian languages"),
                new LanguageHelper(string.Empty, "tut", "Altaic languages"),
                new LanguageHelper("am", "amh", "Amharic"),
                new LanguageHelper(string.Empty, "anp", "Angika"),
                new LanguageHelper(string.Empty, "apa", "Apache languages"),
                new LanguageHelper("ar", "ara", "Arabic"),
                new LanguageHelper("an", "arg", "Aragonese"),
                new LanguageHelper(string.Empty, "arp", "Arapaho"),
                new LanguageHelper(string.Empty, "arw", "Arawak"),
                new LanguageHelper("hy", "arm", "Armenian"),
                new LanguageHelper(string.Empty, "rup", "Aromanian / Arumanian / Macedo-Romanian"),
                new LanguageHelper(string.Empty, "art", "Artificial languages"),
                new LanguageHelper("as", "asm", "Assamese"),
                new LanguageHelper(string.Empty, "ast", "Asturian / Bable / Leonese / Asturleonese"),
                new LanguageHelper(string.Empty, "ath", "Athapascan languages"),
                new LanguageHelper(string.Empty, "aus", "Australian languages"),
                new LanguageHelper(string.Empty, "map", "Austronesian languages"),
                new LanguageHelper("av", "ava", "Avaric"),
                new LanguageHelper("ae", "ave", "Avestan"),
                new LanguageHelper(string.Empty, "awa", "Awadhi"),
                new LanguageHelper("ay", "aym", "Aymara"),
                new LanguageHelper("az", "aze", "Azerbaijani"),
                new LanguageHelper(string.Empty, "ban", "Balinese"),
                new LanguageHelper(string.Empty, "bat", "Baltic languages"),
                new LanguageHelper(string.Empty, "bal", "Baluchi"),
                new LanguageHelper("bm", "bam", "Bambara"),
                new LanguageHelper(string.Empty, "bai", "Bamileke languages"),
                new LanguageHelper(string.Empty, "bad", "Banda languages"),
                new LanguageHelper(string.Empty, "bnt", "Bantu (Other)"),
                new LanguageHelper(string.Empty, "bas", "Basa"),
                new LanguageHelper("ba", "bak", "Bashkir"),
                new LanguageHelper("eu", "baq", "Basque"),
                new LanguageHelper(string.Empty, "btk", "Batak languages"),
                new LanguageHelper(string.Empty, "bej", "Beja / Bedawiyet"),
                new LanguageHelper("be", "bel", "Belarusian"),
                new LanguageHelper(string.Empty, "bem", "Bemba"),
                new LanguageHelper("bn", "ben", "Bengali"),
                new LanguageHelper(string.Empty, "ber", "Berber languages"),
                new LanguageHelper(string.Empty, "bho", "Bhojpuri"),
                new LanguageHelper("bh", "bih", "Bihari languages"),
                new LanguageHelper(string.Empty, "bik", "Bikol"),
                new LanguageHelper(string.Empty, "bin", "Bini / Edo"),
                new LanguageHelper("bi", "bis", "Bislama"),
                new LanguageHelper(string.Empty, "byn", "Blin / Bilin"),
                new LanguageHelper(string.Empty, "zbl", "Blissymbols / Blissymbolics / Bliss"),
                new LanguageHelper("nb", "nob", "Bokmål, Norwegian / Norwegian Bokmål"),
                new LanguageHelper("bs", "bos", "Bosnian"),
                new LanguageHelper(string.Empty, "bra", "Braj"),
                new LanguageHelper("br", "bre", "Breton"),
                new LanguageHelper(string.Empty, "bug", "Buginese"),
                new LanguageHelper("bg", "bul", "Bulgarian"),
                new LanguageHelper(string.Empty, "bua", "Buriat"),
                new LanguageHelper("my", "bur", "Burmese"),
                new LanguageHelper(string.Empty, "cad", "Caddo"),
                new LanguageHelper("ca", "cat", "Catalan / Valencian"),
                new LanguageHelper(string.Empty, "cau", "Caucasian languages"),
                new LanguageHelper(string.Empty, "ceb", "Cebuano"),
                new LanguageHelper(string.Empty, "cel", "Celtic languages"),
                new LanguageHelper(string.Empty, "cai", "Central American Indian languages"),
                new LanguageHelper("km", "khm", "Central Khmer"),
                new LanguageHelper(string.Empty, "chg", "Chagatai"),
                new LanguageHelper(string.Empty, "cmc", "Chamic languages"),
                new LanguageHelper("ch", "cha", "Chamorro"),
                new LanguageHelper("ce", "che", "Chechen"),
                new LanguageHelper(string.Empty, "chr", "Cherokee"),
                new LanguageHelper(string.Empty, "chy", "Cheyenne"),
                new LanguageHelper(string.Empty, "chb", "Chibcha"),
                new LanguageHelper("ny", "nya", "Chichewa / Chewa / Nyanja"),
                new LanguageHelper("zh", "chi", "Chinese"),
                new LanguageHelper(string.Empty, "chn", "Chinook jargon"),
                new LanguageHelper(string.Empty, "chp", "Chipewyan / Dene Suline"),
                new LanguageHelper(string.Empty, "cho", "Choctaw"),
                new LanguageHelper("cu", "chu", "Church Slavic / Old Slavonic / Church Slavonic / Old Bulgarian / Old Church Slavonic"),
                new LanguageHelper(string.Empty, "chk", "Chuukese"),
                new LanguageHelper("cv", "chv", "Chuvash"),
                new LanguageHelper(string.Empty, "nwc", "Classical Newari / Old Newari / Classical Nepal Bhasa"),
                new LanguageHelper(string.Empty, "syc", "Classical Syriac"),
                new LanguageHelper(string.Empty, "cop", "Coptic"),
                new LanguageHelper("kw", "cor", "Cornish"),
                new LanguageHelper("co", "cos", "Corsican"),
                new LanguageHelper("cr", "cre", "Cree"),
                new LanguageHelper(string.Empty, "mus", "Creek"),
                new LanguageHelper(string.Empty, "crp", "Creoles and pidgins"),
                new LanguageHelper(string.Empty, "cpe", "Creoles and pidgins, English based"),
                new LanguageHelper(string.Empty, "cpf", "Creoles and pidgins, French-based"),
                new LanguageHelper(string.Empty, "cpp", "Creoles and pidgins, Portuguese-based"),
                new LanguageHelper(string.Empty, "crh", "Crimean Tatar / Crimean Turkish"),
                new LanguageHelper("hr", "hrv", "Croatian"),
                new LanguageHelper(string.Empty, "cus", "Cushitic languages"),
                new LanguageHelper("cs", "cze", "Czech"),
                new LanguageHelper(string.Empty, "dak", "Dakota"),
                new LanguageHelper("da", "dan", "Danish"),
                new LanguageHelper(string.Empty, "dar", "Dargwa"),
                new LanguageHelper(string.Empty, "del", "Delaware"),
                new LanguageHelper(string.Empty, "din", "Dinka"),
                new LanguageHelper("dv", "div", "Divehi / Dhivehi / Maldivian"),
                new LanguageHelper(string.Empty, "doi", "Dogri"),
                new LanguageHelper(string.Empty, "dgr", "Dogrib"),
                new LanguageHelper(string.Empty, "dra", "Dravidian languages"),
                new LanguageHelper(string.Empty, "dua", "Duala"),
                new LanguageHelper(string.Empty, "dum", "Dutch, Middle (ca.1050-1350)"),
                new LanguageHelper("nl", "dut", "Dutch / Flemish"),
                new LanguageHelper(string.Empty, "dyu", "Dyula"),
                new LanguageHelper("dz", "dzo", "Dzongkha"),
                new LanguageHelper(string.Empty, "frs", "Eastern Frisian"),
                new LanguageHelper(string.Empty, "efi", "Efik"),
                new LanguageHelper(string.Empty, "egy", "Egyptian (Ancient)"),
                new LanguageHelper(string.Empty, "eka", "Ekajuk"),
                new LanguageHelper(string.Empty, "elx", "Elamite"),
                new LanguageHelper("en", "eng", "English"),
                new LanguageHelper(string.Empty, "enm", "English, Middle (1100-1500)"),
                new LanguageHelper(string.Empty, "ang", "English, Old (ca.450-1100)"),
                new LanguageHelper(string.Empty, "myv", "Erzya"),
                new LanguageHelper("eo", "epo", "Esperanto"),
                new LanguageHelper("et", "est", "Estonian"),
                new LanguageHelper("ee", "ewe", "Ewe"),
                new LanguageHelper(string.Empty, "ewo", "Ewondo"),
                new LanguageHelper(string.Empty, "fan", "Fang"),
                new LanguageHelper(string.Empty, "fat", "Fanti"),
                new LanguageHelper("fo", "fao", "Faroese"),
                new LanguageHelper("fj", "fij", "Fijian"),
                new LanguageHelper(string.Empty, "fil", "Filipino / Pilipino"),
                new LanguageHelper("fi", "fin", "Finnish"),
                new LanguageHelper(string.Empty, "fiu", "Finno-Ugrian languages"),
                new LanguageHelper(string.Empty, "fon", "Fon"),
                new LanguageHelper("fr", "fre", "French"),
                new LanguageHelper(string.Empty, "frm", "French, Middle (ca.1400-1600)"),
                new LanguageHelper(string.Empty, "fro", "French, Old (842-ca.1400)"),
                new LanguageHelper(string.Empty, "fur", "Friulian"),
                new LanguageHelper("ff", "ful", "Fulah"),
                new LanguageHelper(string.Empty, "gaa", "Ga"),
                new LanguageHelper("gd", "gla", "Gaelic / Scottish Gaelic"),
                new LanguageHelper(string.Empty, "car", "Galibi Carib"),
                new LanguageHelper("gl", "glg", "Galician"),
                new LanguageHelper("lg", "lug", "Ganda"),
                new LanguageHelper(string.Empty, "gay", "Gayo"),
                new LanguageHelper(string.Empty, "gba", "Gbaya"),
                new LanguageHelper(string.Empty, "gez", "Geez"),
                new LanguageHelper("ka", "geo", "Georgian"),
                new LanguageHelper("de", "ger", "German"),
                new LanguageHelper("de", "deu", "German"),
                new LanguageHelper(string.Empty, "gmh", "German, Middle High (ca.1050-1500)"),
                new LanguageHelper(string.Empty, "goh", "German, Old High (ca.750-1050)"),
                new LanguageHelper(string.Empty, "gem", "Germanic languages"),
                new LanguageHelper(string.Empty, "gil", "Gilbertese"),
                new LanguageHelper(string.Empty, "gon", "Gondi"),
                new LanguageHelper(string.Empty, "gor", "Gorontalo"),
                new LanguageHelper(string.Empty, "got", "Gothic"),
                new LanguageHelper(string.Empty, "grb", "Grebo"),
                new LanguageHelper(string.Empty, "grc", "Greek, Ancient (to 1453)"),
                new LanguageHelper("el", "gre", "Greek, Modern (1453-)"),
                new LanguageHelper("gn", "grn", "Guarani"),
                new LanguageHelper("gu", "guj", "Gujarati"),
                new LanguageHelper(string.Empty, "gwi", "Gwich'in"),
                new LanguageHelper(string.Empty, "hai", "Haida"),
                new LanguageHelper("ht", "hat", "Haitian / Haitian Creole"),
                new LanguageHelper("ha", "hau", "Hausa"),
                new LanguageHelper(string.Empty, "haw", "Hawaiian"),
                new LanguageHelper("he", "heb", "Hebrew"),
                new LanguageHelper("hz", "her", "Herero"),
                new LanguageHelper(string.Empty, "hil", "Hiligaynon"),
                new LanguageHelper(string.Empty, "him", "Himachali languages / Western Pahari languages"),
                new LanguageHelper("hi", "hin", "Hindi"),
                new LanguageHelper("ho", "hmo", "Hiri Motu"),
                new LanguageHelper(string.Empty, "hit", "Hittite"),
                new LanguageHelper(string.Empty, "hmn", "Hmong / Mong"),
                new LanguageHelper("hu", "hun", "Hungarian"),
                new LanguageHelper(string.Empty, "hup", "Hupa"),
                new LanguageHelper(string.Empty, "iba", "Iban"),
                new LanguageHelper("is", "ice", "Icelandic"),
                new LanguageHelper("io", "ido", "Ido"),
                new LanguageHelper("ig", "ibo", "Igbo"),
                new LanguageHelper(string.Empty, "ijo", "Ijo languages"),
                new LanguageHelper(string.Empty, "ilo", "Iloko"),
                new LanguageHelper(string.Empty, "smn", "Inari Sami"),
                new LanguageHelper(string.Empty, "inc", "Indic languages"),
                new LanguageHelper(string.Empty, "ine", "Indo-European languages"),
                new LanguageHelper("id", "ind", "Indonesian"),
                new LanguageHelper(string.Empty, "inh", "Ingush"),
                new LanguageHelper("ia", "ina", "Interlingua (International Auxiliary Language Association)"),
                new LanguageHelper("ie", "ile", "Interlingue / Occidental"),
                new LanguageHelper("iu", "iku", "Inuktitut"),
                new LanguageHelper("ik", "ipk", "Inupiaq"),
                new LanguageHelper(string.Empty, "ira", "Iranian languages"),
                new LanguageHelper("ga", "gle", "Irish"),
                new LanguageHelper(string.Empty, "mga", "Irish, Middle (900-1200)"),
                new LanguageHelper(string.Empty, "sga", "Irish, Old (to 900)"),
                new LanguageHelper(string.Empty, "iro", "Iroquoian languages"),
                new LanguageHelper("it", "ita", "Italian"),
                new LanguageHelper("ja", "jpn", "Japanese"),
                new LanguageHelper("jv", "jav", "Javanese"),
                new LanguageHelper(string.Empty, "jrb", "Judeo-Arabic"),
                new LanguageHelper(string.Empty, "jpr", "Judeo-Persian"),
                new LanguageHelper(string.Empty, "kbd", "Kabardian"),
                new LanguageHelper(string.Empty, "kab", "Kabyle"),
                new LanguageHelper(string.Empty, "kac", "Kachin / Jingpho"),
                new LanguageHelper("kl", "kal", "Kalaallisut / Greenlandic"),
                new LanguageHelper(string.Empty, "xal", "Kalmyk / Oirat"),
                new LanguageHelper(string.Empty, "kam", "Kamba"),
                new LanguageHelper("kn", "kan", "Kannada"),
                new LanguageHelper("kr", "kau", "Kanuri"),
                new LanguageHelper(string.Empty, "kaa", "Kara-Kalpak"),
                new LanguageHelper(string.Empty, "krc", "Karachay-Balkar"),
                new LanguageHelper(string.Empty, "krl", "Karelian"),
                new LanguageHelper(string.Empty, "kar", "Karen languages"),
                new LanguageHelper("ks", "kas", "Kashmiri"),
                new LanguageHelper(string.Empty, "csb", "Kashubian"),
                new LanguageHelper(string.Empty, "kaw", "Kawi"),
                new LanguageHelper("kk", "kaz", "Kazakh"),
                new LanguageHelper(string.Empty, "kha", "Khasi"),
                new LanguageHelper(string.Empty, "khi", "Khoisan languages"),
                new LanguageHelper(string.Empty, "kho", "Khotanese / Sakan"),
                new LanguageHelper("ki", "kik", "Kikuyu / Gikuyu"),
                new LanguageHelper(string.Empty, "kmb", "Kimbundu"),
                new LanguageHelper("rw", "kin", "Kinyarwanda"),
                new LanguageHelper("ky", "kir", "Kirghiz / Kyrgyz"),
                new LanguageHelper(string.Empty, "tlh", "Klingon / tlhIngan-Hol"),
                new LanguageHelper("kv", "kom", "Komi"),
                new LanguageHelper("kg", "kon", "Kongo"),
                new LanguageHelper(string.Empty, "kok", "Konkani"),
                new LanguageHelper("ko", "kor", "Korean"),
                new LanguageHelper(string.Empty, "kos", "Kosraean"),
                new LanguageHelper(string.Empty, "kpe", "Kpelle"),
                new LanguageHelper(string.Empty, "kro", "Kru languages"),
                new LanguageHelper("kj", "kua", "Kuanyama / Kwanyama"),
                new LanguageHelper(string.Empty, "kum", "Kumyk"),
                new LanguageHelper("ku", "kur", "Kurdish"),
                new LanguageHelper(string.Empty, "kru", "Kurukh"),
                new LanguageHelper(string.Empty, "kut", "Kutenai"),
                new LanguageHelper(string.Empty, "lad", "Ladino"),
                new LanguageHelper(string.Empty, "lah", "Lahnda"),
                new LanguageHelper(string.Empty, "lam", "Lamba"),
                new LanguageHelper(string.Empty, "day", "Land Dayak languages"),
                new LanguageHelper("lo", "lao", "Lao"),
                new LanguageHelper("la", "lat", "Latin"),
                new LanguageHelper("lv", "lav", "Latvian"),
                new LanguageHelper(string.Empty, "lez", "Lezghian"),
                new LanguageHelper("li", "lim", "Limburgan / Limburger / Limburgish"),
                new LanguageHelper("ln", "lin", "Lingala"),
                new LanguageHelper("lt", "lit", "Lithuanian"),
                new LanguageHelper(string.Empty, "jbo", "Lojban"),
                new LanguageHelper(string.Empty, "nds", "Low German / Low Saxon / German, Low / Saxon, Low"),
                new LanguageHelper(string.Empty, "dsb", "Lower Sorbian"),
                new LanguageHelper(string.Empty, "loz", "Lozi"),
                new LanguageHelper("lu", "lub", "Luba-Katanga"),
                new LanguageHelper(string.Empty, "lua", "Luba-Lulua"),
                new LanguageHelper(string.Empty, "lui", "Luiseno"),
                new LanguageHelper(string.Empty, "smj", "Lule Sami"),
                new LanguageHelper(string.Empty, "lun", "Lunda"),
                new LanguageHelper(string.Empty, "luo", "Luo (Kenya and Tanzania)"),
                new LanguageHelper(string.Empty, "lus", "Lushai"),
                new LanguageHelper("lb", "ltz", "Luxembourgish / Letzeburgesch"),
                new LanguageHelper("mk", "mac", "Macedonian"),
                new LanguageHelper(string.Empty, "mad", "Madurese"),
                new LanguageHelper(string.Empty, "mag", "Magahi"),
                new LanguageHelper(string.Empty, "mai", "Maithili"),
                new LanguageHelper(string.Empty, "mak", "Makasar"),
                new LanguageHelper("mg", "mlg", "Malagasy"),
                new LanguageHelper("ms", "may", "Malay"),
                new LanguageHelper("ml", "mal", "Malayalam"),
                new LanguageHelper("mt", "mlt", "Maltese"),
                new LanguageHelper(string.Empty, "mnc", "Manchu"),
                new LanguageHelper(string.Empty, "mdr", "Mandar"),
                new LanguageHelper(string.Empty, "man", "Mandingo"),
                new LanguageHelper(string.Empty, "mni", "Manipuri"),
                new LanguageHelper(string.Empty, "mno", "Manobo languages"),
                new LanguageHelper("gv", "glv", "Manx"),
                new LanguageHelper("mi", "mao", "Maori"),
                new LanguageHelper(string.Empty, "arn", "Mapudungun / Mapuche"),
                new LanguageHelper("mr", "mar", "Marathi"),
                new LanguageHelper(string.Empty, "chm", "Mari"),
                new LanguageHelper("mh", "mah", "Marshallese"),
                new LanguageHelper(string.Empty, "mwr", "Marwari"),
                new LanguageHelper(string.Empty, "mas", "Masai"),
                new LanguageHelper(string.Empty, "myn", "Mayan languages"),
                new LanguageHelper(string.Empty, "men", "Mende"),
                new LanguageHelper(string.Empty, "mic", "Mi'kmaq / Micmac"),
                new LanguageHelper(string.Empty, "min", "Minangkabau"),
                new LanguageHelper(string.Empty, "mwl", "Mirandese"),
                new LanguageHelper(string.Empty, "moh", "Mohawk"),
                new LanguageHelper(string.Empty, "mdf", "Moksha"),
                new LanguageHelper(string.Empty, "mkh", "Mon-Khmer languages"),
                new LanguageHelper(string.Empty, "lol", "Mongo"),
                new LanguageHelper("mn", "mon", "Mongolian"),
                new LanguageHelper(string.Empty, "mos", "Mossi"),
                new LanguageHelper(string.Empty, "mul", "Multiple languages"),
                new LanguageHelper(string.Empty, "mun", "Munda languages"),
                new LanguageHelper(string.Empty, "nqo", "N'Ko"),
                new LanguageHelper(string.Empty, "nah", "Nahuatl languages"),
                new LanguageHelper("na", "nau", "Nauru"),
                new LanguageHelper("nv", "nav", "Navajo / Navaho"),
                new LanguageHelper("nd", "nde", "Ndebele, North / North Ndebele"),
                new LanguageHelper("nr", "nbl", "Ndebele, South / South Ndebele"),
                new LanguageHelper("ng", "ndo", "Ndonga"),
                new LanguageHelper(string.Empty, "nap", "Neapolitan"),
                new LanguageHelper(string.Empty, "new", "Nepal Bhasa / Newari"),
                new LanguageHelper("ne", "nep", "Nepali"),
                new LanguageHelper(string.Empty, "nia", "Nias"),
                new LanguageHelper(string.Empty, "nic", "Niger-Kordofanian languages"),
                new LanguageHelper(string.Empty, "ssa", "Nilo-Saharan languages"),
                new LanguageHelper(string.Empty, "niu", "Niuean"),
                new LanguageHelper(string.Empty, "zxx", "No linguistic content / Not applicable"),
                new LanguageHelper(string.Empty, "nog", "Nogai"),
                new LanguageHelper(string.Empty, "non", "Norse, Old"),
                new LanguageHelper(string.Empty, "nai", "North American Indian languages"),
                new LanguageHelper(string.Empty, "frr", "Northern Frisian"),
                new LanguageHelper("se", "sme", "Northern Sami"),
                new LanguageHelper("nn", "nno", "Norwegian Nynorsk / Nynorsk, Norwegian"),
                new LanguageHelper("no", "nor", "Norwegian"),
                new LanguageHelper(string.Empty, "nub", "Nubian languages"),
                new LanguageHelper(string.Empty, "nym", "Nyamwezi"),
                new LanguageHelper(string.Empty, "nyn", "Nyankole"),
                new LanguageHelper(string.Empty, "nyo", "Nyoro"),
                new LanguageHelper(string.Empty, "nzi", "Nzima"),
                new LanguageHelper("oc", "oci", "Occitan (post 1500)"),
                new LanguageHelper(string.Empty, "arc", "Official Aramaic (700-300 BCE) / Imperial Aramaic (700-300 BCE)"),
                new LanguageHelper("oj", "oji", "Ojibwa"),
                new LanguageHelper("or", "ori", "Oriya"),
                new LanguageHelper("om", "orm", "Oromo"),
                new LanguageHelper(string.Empty, "osa", "Osage"),
                new LanguageHelper("os", "oss", "Ossetian / Ossetic"),
                new LanguageHelper(string.Empty, "oto", "Otomian languages"),
                new LanguageHelper(string.Empty, "pal", "Pahlavi"),
                new LanguageHelper(string.Empty, "pau", "Palauan"),
                new LanguageHelper("pi", "pli", "Pali"),
                new LanguageHelper(string.Empty, "pam", "Pampanga / Kapampangan"),
                new LanguageHelper(string.Empty, "pag", "Pangasinan"),
                new LanguageHelper("pa", "pan", "Panjabi / Punjabi"),
                new LanguageHelper(string.Empty, "pap", "Papiamento"),
                new LanguageHelper(string.Empty, "paa", "Papuan languages"),
                new LanguageHelper(string.Empty, "nso", "Pedi / Sepedi / Northern Sotho"),
                new LanguageHelper("fa", "per", "Persian"),
                new LanguageHelper(string.Empty, "peo", "Persian, Old (ca.600-400 B.C.)"),
                new LanguageHelper(string.Empty, "phi", "Philippine languages"),
                new LanguageHelper(string.Empty, "phn", "Phoenician"),
                new LanguageHelper(string.Empty, "pon", "Pohnpeian"),
                new LanguageHelper("pl", "pol", "Polish"),
                new LanguageHelper("pt", "por", "Portuguese"),
                new LanguageHelper(string.Empty, "pra", "Prakrit languages"),
                new LanguageHelper(string.Empty, "pro", "Provençal, Old (to 1500) / Occitan, Old (to 1500)"),
                new LanguageHelper("ps", "pus", "Pushto / Pashto"),
                new LanguageHelper("qu", "que", "Quechua"),
                new LanguageHelper(string.Empty, "raj", "Rajasthani"),
                new LanguageHelper(string.Empty, "rap", "Rapanui"),
                new LanguageHelper(string.Empty, "rar", "Rarotongan / Cook Islands Maori"),
                new LanguageHelper(string.Empty, "roa", "Romance languages"),
                new LanguageHelper("ro", "rum", "Romanian / Moldavian / Moldovan"),
                new LanguageHelper("rm", "roh", "Romansh"),
                new LanguageHelper(string.Empty, "rom", "Romany"),
                new LanguageHelper("rn", "run", "Rundi"),
                new LanguageHelper("ru", "rus", "Russian"),
                new LanguageHelper(string.Empty, "sal", "Salishan languages"),
                new LanguageHelper(string.Empty, "sam", "Samaritan Aramaic"),
                new LanguageHelper(string.Empty, "smi", "Sami languages"),
                new LanguageHelper("sm", "smo", "Samoan"),
                new LanguageHelper(string.Empty, "sad", "Sandawe"),
                new LanguageHelper("sg", "sag", "Sango"),
                new LanguageHelper("sa", "san", "Sanskrit"),
                new LanguageHelper(string.Empty, "sat", "Santali"),
                new LanguageHelper("sc", "srd", "Sardinian"),
                new LanguageHelper(string.Empty, "sas", "Sasak"),
                new LanguageHelper(string.Empty, "sco", "Scots"),
                new LanguageHelper(string.Empty, "sel", "Selkup"),
                new LanguageHelper(string.Empty, "sem", "Semitic languages"),
                new LanguageHelper("sr", "srp", "Serbian"),
                new LanguageHelper(string.Empty, "srr", "Serer"),
                new LanguageHelper(string.Empty, "shn", "Shan"),
                new LanguageHelper("sn", "sna", "Shona"),
                new LanguageHelper("ii", "iii", "Sichuan Yi / Nuosu"),
                new LanguageHelper(string.Empty, "scn", "Sicilian"),
                new LanguageHelper(string.Empty, "sid", "Sidamo"),
                new LanguageHelper(string.Empty, "sgn", "Sign Languages"),
                new LanguageHelper(string.Empty, "bla", "Siksika"),
                new LanguageHelper("sd", "snd", "Sindhi"),
                new LanguageHelper("si", "sin", "Sinhala / Sinhalese"),
                new LanguageHelper(string.Empty, "sit", "Sino-Tibetan languages"),
                new LanguageHelper(string.Empty, "sio", "Siouan languages"),
                new LanguageHelper(string.Empty, "sms", "Skolt Sami"),
                new LanguageHelper(string.Empty, "den", "Slave (Athapascan)"),
                new LanguageHelper(string.Empty, "sla", "Slavic languages"),
                new LanguageHelper("sk", "slo", "Slovak"),
                new LanguageHelper("sl", "slv", "Slovenian"),
                new LanguageHelper(string.Empty, "sog", "Sogdian"),
                new LanguageHelper("so", "som", "Somali"),
                new LanguageHelper(string.Empty, "son", "Songhai languages"),
                new LanguageHelper(string.Empty, "snk", "Soninke"),
                new LanguageHelper(string.Empty, "wen", "Sorbian languages"),
                new LanguageHelper("st", "sot", "Sotho, Southern"),
                new LanguageHelper(string.Empty, "sai", "South American Indian (Other)"),
                new LanguageHelper(string.Empty, "alt", "Southern Altai"),
                new LanguageHelper(string.Empty, "sma", "Southern Sami"),
                new LanguageHelper("es", "spa", "Spanish / Castillan"),
                new LanguageHelper(string.Empty, "srn", "Sranan Tongo"),
                new LanguageHelper(string.Empty, "suk", "Sukuma"),
                new LanguageHelper(string.Empty, "sux", "Sumerian"),
                new LanguageHelper("su", "sun", "Sundanese"),
                new LanguageHelper(string.Empty, "sus", "Susu"),
                new LanguageHelper("sw", "swa", "Swahili"),
                new LanguageHelper("ss", "ssw", "Swati"),
                new LanguageHelper("sv", "swe", "Swedish"),
                new LanguageHelper(string.Empty, "gsw", "Swiss German / Alemannic / Alsatian"),
                new LanguageHelper(string.Empty, "syr", "Syriac"),
                new LanguageHelper("tl", "tgl", "Tagalog"),
                new LanguageHelper("ty", "tah", "Tahitian"),
                new LanguageHelper(string.Empty, "tai", "Tai languages"),
                new LanguageHelper("tg", "tgk", "Tajik"),
                new LanguageHelper(string.Empty, "tmh", "Tamashek"),
                new LanguageHelper("ta", "tam", "Tamil"),
                new LanguageHelper("tt", "tat", "Tatar"),
                new LanguageHelper("te", "tel", "Telugu"),
                new LanguageHelper(string.Empty, "ter", "Tereno"),
                new LanguageHelper(string.Empty, "tet", "Tetum"),
                new LanguageHelper("th", "tha", "Thai"),
                new LanguageHelper("bo", "tib", "Tibetan"),
                new LanguageHelper(string.Empty, "tig", "Tigre"),
                new LanguageHelper("ti", "tir", "Tigrinya"),
                new LanguageHelper(string.Empty, "tem", "Timne"),
                new LanguageHelper(string.Empty, "tiv", "Tiv"),
                new LanguageHelper(string.Empty, "tli", "Tlingit"),
                new LanguageHelper(string.Empty, "tpi", "Tok Pisin"),
                new LanguageHelper(string.Empty, "tkl", "Tokelau"),
                new LanguageHelper(string.Empty, "tog", "Tonga (Nyasa)"),
                new LanguageHelper("to", "ton", "Tonga (Tonga Islands)"),
                new LanguageHelper(string.Empty, "tsi", "Tsimshian"),
                new LanguageHelper("ts", "tso", "Tsonga"),
                new LanguageHelper("tn", "tsn", "Tswana"),
                new LanguageHelper(string.Empty, "tum", "Tumbuka"),
                new LanguageHelper(string.Empty, "tup", "Tupi languages"),
                new LanguageHelper("tr", "tur", "Turkish"),
                new LanguageHelper(string.Empty, "ota", "Turkish, Ottoman (1500-1928)"),
                new LanguageHelper("tk", "tuk", "Turkmen"),
                new LanguageHelper(string.Empty, "tvl", "Tuvalu"),
                new LanguageHelper(string.Empty, "tyv", "Tuvinian"),
                new LanguageHelper("tw", "twi", "Twi"),
                new LanguageHelper(string.Empty, "udm", "Udmurt"),
                new LanguageHelper(string.Empty, "uga", "Ugaritic"),
                new LanguageHelper("ug", "uig", "Uighur / Uyghur"),
                new LanguageHelper("uk", "ukr", "Ukrainian"),
                new LanguageHelper(string.Empty, "umb", "Umbundu"),
                new LanguageHelper(string.Empty, "mis", "Uncoded languages"),
                new LanguageHelper(string.Empty, "und", "Undetermined"),
                new LanguageHelper(string.Empty, "hsb", "Upper Sorbian"),
                new LanguageHelper("ur", "urd", "Urdu"),
                new LanguageHelper("uz", "uzb", "Uzbek"),
                new LanguageHelper(string.Empty, "vai", "Vai"),
                new LanguageHelper("ve", "ven", "Venda"),
                new LanguageHelper("vi", "vie", "Vietnamese"),
                new LanguageHelper("vo", "vol", "Volapük"),
                new LanguageHelper(string.Empty, "vot", "Votic"),
                new LanguageHelper(string.Empty, "wak", "Wakashan languages"),
                new LanguageHelper(string.Empty, "wal", "Walamo"),
                new LanguageHelper("wa", "wln", "Walloon"),
                new LanguageHelper(string.Empty, "war", "Waray"),
                new LanguageHelper(string.Empty, "was", "Washo"),
                new LanguageHelper("cy", "wel", "Welsh"),
                new LanguageHelper("fy", "fry", "Western Frisian"),
                new LanguageHelper("wo", "wol", "Wolof"),
                new LanguageHelper("xh", "xho", "Xhosa"),
                new LanguageHelper(string.Empty, "sah", "Yakut"),
                new LanguageHelper(string.Empty, "yao", "Yao"),
                new LanguageHelper(string.Empty, "yap", "Yapese"),
                new LanguageHelper("yi", "yid", "Yiddish"),
                new LanguageHelper("yo", "yor", "Yoruba"),
                new LanguageHelper(string.Empty, "ypk", "Yupik languages"),
                new LanguageHelper(string.Empty, "znd", "Zande languages"),
                new LanguageHelper(string.Empty, "zap", "Zapotec"),
                new LanguageHelper(string.Empty, "zza", "Zaza / Dimili / Dimli / Kirdki / Kirmanjki / Zazaki"),
                new LanguageHelper(string.Empty, "zen", "Zenaga"),
                new LanguageHelper("za", "zha", "Zhuang / Chuang"),
                new LanguageHelper("zu", "zul", "Zulu"),
                new LanguageHelper(string.Empty, "zun", "Zuni"),
                new LanguageHelper("xx", "xxx", "Undefined")
            };

            return langList;
        }
    }
}
